### ISSUE TITLE
Error: Resource not accessible by integration

### ISSUE THREAD

**Issue by borecz** [allure-framework/setup-allurectl#138]
I am getting error `Error: Resource not accessible by integration` when trying to use GH action `allure-framework/setup-allurectl@v1`

My Github action file looks something like 

```
- name: Set up JDK 1.8
  uses: actions/setup-java@v1
   with:
      java-version: 1.8

- name: install and configure allurectl
  uses: allure-framework/setup-allurectl@v1
  with:
     allure-endpoint: https://testing.allure.aws.qameta.in
     allure-token: ${{ secrets.ALLURE_TOKEN }}
     allure-project-id: ${{ secrets.ALLURE_PROJECT_ID }}
```

Error displayed on GH action is 

```
Run allure-framework/setup-allurectl@v***
  with:
    allure-endpoint: https://testing.allure.aws.qameta.in
    allure-token: ***
    allure-project-id: ***
    allurectl-version: latest
    github-token: ***
  env:
    ENVIRONMENT: QA
    QA_URL: ***
    QA_USERNAME: ***
    QA_PASSWORD: ***
    PROD_URL: 
    PROD_USERNAME: 
    PROD_PASSWORD: 
    SLACK_BOT_USER_OAUTH_TOKEN: ***
    ***: true
    ALLURE_ENDPOINT: ***
    ALLURE_TOKEN: ***
    ALLURE_PROJECT_ID: ***
    ALLURE_LAUNCH_NAME: ***
    ALLURE_JOB_RUN_ID: 
    PNPM_HOME: /home/runner/setup-pnpm/node_modules/.bin
    JAVA_HOME_8.0.39[2](https://github.com/BenefitFlow/Benefit-Flow.E2E/actions/runs/6612749741/job/17959230270#step:11:2)_x64: /opt/hostedtoolcache/jdk/8.0.[3](https://github.com/BenefitFlow/Benefit-Flow.E2E/actions/runs/6612749741/job/17959230270#step:11:3)92/x6[4](https://github.com/BenefitFlow/Benefit-Flow.E2E/actions/runs/6612749741/job/17959230270#step:11:4)
    JAVA_HOME: /opt/hostedtoolcache/jdk/8.0.392/x64
    JAVA_HOME_8_0_392_X64: /opt/hostedtoolcache/jdk/8.0.392/x64
version: 2.***[5](https://github.com/BenefitFlow/Benefit-Flow.E2E/actions/runs/6612749741/job/17959230270#step:11:5).***
platform: linux/amd[6](https://github.com/BenefitFlow/Benefit-Flow.E2E/actions/runs/6612749741/job/17959230270#step:11:6)4
download: https://github.com/allure-framework/allurectl/releases/download/2.***5.***/allurectl_linux_amd64
/opt/hostedtoolcache/allurectl/2.***5.***/amd64/allurectl --version
allurectl version 2.***5.***
Error: Resource not accessible by integration
```
